Build powerpc64 with -Wno-stringop-overflow tests due to false positives
They do seem to be false positives when I look through the code, and
it is also independently reported here:
https://bugs.launchpad.net/ubuntu/+source/gcc-12/+bug/2013140

The warnings disappear at -O2, but compilation and tests seem fine at
-O3 with the warning disabled, so I chose to keep it at -O3.

An example warning is:

```
In file included from native/poly1305-donna.c:11:
native/poly1305-donna.c: In function ‘mc_poly1305_update’:
native/poly1305-donna-64.h:24:23: note: at offset 28 into destination object ‘buffer’ of size 16
   24 |         unsigned char buffer[poly1305_block_size];
      |                       ^~~~~~
In function ‘poly1305_update’,
    inlined from ‘mc_poly1305_update’ at native/poly1305-donna.c:60:3:
native/poly1305-donna.c:48:54: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
   48 |                         st->buffer[st->leftover + i] = m[i];
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
```